version: '3'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    environment:
      MCP_BRAVE_API_KEY: BSALlBoimbUoUmwZ3Wn8wdvEKISuTJa
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: "true"
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
